#!/bin/bash

function trim {
    local var="$*"
    # remove leading whitespace characters
    var="${var#"${var%%[![:space:]]*}"}"
    # remove trailing whitespace characters
    var="${var%"${var##*[![:space:]]}"}"   
    printf '%s' "$var"
}

#https://wiki.archlinux.org/index.php/Bluetooth_headset
#
#bluetoothctl
#
#power on
#agent on
#default-agent
#scan on
#
#pair 00:1D:43:6D:03:26
#connect 00:1D:43:6D:03:26
#scan off
#exit

#bluetoothctl connect 0C:E0:E4:23:BB:86
powered=$(bluetoothctl show | grep "Powered:" | cut -d":" -f2)
if [[ $powered == *no* ]]; then
    printf '%s\n' "-"
else
    status=$(bluetoothctl info | grep 'Alias: ' | cut -d":" -f2-)
    if [ -n "$status" ]; then
        name=$(trim $status)
        name=${name// /_}
        printf "= %s\n" "$name"
    else
        printf "+\n"
    fi
fi

