#!/usr/bin/env bash


#https://wiki.archlinux.org/index.php/Bluetooth_headset
#
#bluetoothctl
#
#power on
#agent on
#default-agent
#scan on
#
#pair 00:1D:43:6D:03:26
#connect 00:1D:43:6D:03:26
#scan off
#exit

#bluetoothctl connect 0C:E0:E4:23:BB:86
icon=""
powered=$(bluetoothctl show | grep "Powered:" | cut -d":" -f2)
if [[ $powered == *no* ]]; then
    icon=""
else
    status=$(bluetoothctl info | grep 'Alias: ' | cut -d":" -f2-)
    if [ -n "$status" ]; then
        icon=""
    else
        icon=""
    fi
fi

printf "%s\n" "$icon"
