#!/bin/bash

function trim {
    local var="$*"
    # remove leading whitespace characters
    var="${var#"${var%%[![:space:]]*}"}"
    # remove trailing whitespace characters
    var="${var%"${var##*[![:space:]]}"}"   
    printf '%s' "$var"
}

function send_notification {
  dunstify -a bluetooth -t 3000 -r 2605 -u normal "$*"
}

#https://wiki.archlinux.org/index.php/Bluetooth_headset
powered=$(bluetoothctl show | grep "Powered:" | cut -d":" -f2)
if [[ $powered == *no* ]]; then
    send_notification ""
else
    status=$(bluetoothctl info | grep 'Alias: ' | cut -d":" -f2-)
    if [ -n "$status" ]; then
        name=$(trim $status)
        name=${name// /_}
        send_notification " $name"
    else
        send_notification ""
    fi
fi

